package com.silent.core.utils

const val NV99_URL = "https://nv99.com.br/"
const val YOUTUBE_WATCH_PREFIX = "https://www.youtube.com/watch?v="
const val YOUTUBE_CHANNEL_PREFIX = "https://www.youtube.com/channel/"
const val YOUTUBE_PLAYLIST_PREFIX = "https://www.youtube.com/playlist?list="
const val INSTAGRAM_PREFIX = "https://www.instagram.com/"
const val TWITCH_PREFIX = "https://www.twitch.tv/"
const val TWITTER_PREFIX = "https://twitter.com/"
const val PODCASTS_PREFERENCES = "PODCASTS_PREFERENCES"
const val WARNING_PREFERENCE = "WARNING_PREFERENCE"
const val TOKEN_PREFERENCES = "FTOKEN"
const val VIDEOS_PATH = "Videos"
const val CUTS_PATH = "Cuts"
const val USERS_PATH = "Users"
const val PODCASTS_PATH = "Podcasts"
const val HOME_ACT = "com.silent.sparky.features.home.HomeActivity"